### PR TITLE
[doc] Fix typo in README installation section

### PR DESCRIPTION
**Pull request by harshalmittal4**
This code fixes a typo in the command to install the requirements for tests.

### CODE REVIEW

**Comment by harshalmittal4** [comment]
Yup, sure, sorry for skipping the commit msg. Done!

**Comment by valeriocos** [comment]
no worries. Maybe I'm wrong but I don't see the changes in the commit, just in the PR title and description.

**Comment by valeriocos** [comment]
@harshalmittal4 ping

**Comment by valeriocos** [comment]
almost ready @harshalmittal4 :) I see that the commit msg is not complete, it should look like:

```
[doc] Fix typo in README installation section

This code fixes a typo in the command to install the requirements for tests.
```

Thank you!

**Comment by harshalmittal4** [comment]
Hey @valeriocos, is all good now (Sorry for having to use -f push again) !

**Comment by valeriocos** [comment]
Thank you @harshalmittal4 , I have just merged it.

**Pull request closed without merging**
