### PR TITLE
[finos-meeting] New Perceval backend to index FINOS meetings attendance

### PR DESCRIPTION
**Pull request by maoo**
FINOS uses Perceval (via Bitergia) to track community metrics; one very important datapoint for our community is meeting attendance; we track meeting rosters in Confluence, using tables; see an example on https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/915439618/2019-02-27+Meeting+notes and sibling pages.

    In order to understand who participated to which meeting, FINOS have extracted meeting attendance in a CSV file with the following column definition: 'email', 'name', 'org', 'githubid', 'program', 'activity' and 'date'

    The 'finos-meeting' Perceval backend is able to:
    - Parse the 'finos-meetings' CSV structure
    - Customise configuration, to adapt to other CSV structures
    - Parse dates using a configurable list of date formats

### CODE REVIEW

**Comment by sduenas** [comment]
Sorry, @maoo I pushed an edited version of your commit to your branch. It improves the code. The problem is as you make the PR from your master branch, when I pushed the changes GitHub automatically closed the PR.

Can you open a new PR with the changes I included from a new branch?

**Comment by maoo** [comment]
Thanks @sduenas ! I tried to resend the PR, but it says that `This branch is even with Bitergia:master`, from `master` branch on https://github.com/maoo/grimoirelab-perceval-finoss .

Maybe I'm missing something obvious, could you be more specific? TY!

**Comment by sduenas** [comment]
Ok, no worries. I think you had to create a branch from your master branch and then push it. Anyway, I just pushed the changes to master. We can set this PR as merged. The next step is to create an index with this data.

**Comment by maoo** [comment]
Thanks @sduenas. Please let me know if / how I can help with next steps.

**Pull request closed without merging**
